name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "MAIL_MAILER=${{ secrets.MAIL_MAILER }}" >> .env
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env

      - name: Build docker image
        run: docker build -t kirarwa/ist-feedback .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push kirarwa/ist-feedback:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: docker pull kirarwa/ist-feedback:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container kirarwa/ist-feedback
      - name: Run migrations
        run: docker exec nextjs-app-container npm run migrate
      - name: Run seeders
        run: docker exec nextjs-app-container npm run seed 